spring:
  profiles:
    include: secret, s3
  thymeleaf:
    cache: 'false'

  jpa:
    properties:
      hibernate:
        show_sql: true
        use_sql_comments: true
        format_sql: true
    open-in-view: true
    hibernate:
      ddl-auto: update