spring:
  datasource:
    url: jdbc:mysql://hologramdb.cjzh2cslqztl.ap-northeast-2.rds.amazonaws.com:3306/HologramDB
    username: root
    password: hologram123
    driver-class-name: com.mysql.cj.jdbc.Driver


jwt:
  secret:
    key: 7ZWt7ZW0OTntmZTsnbTtjIXtlZzqta3snYTrhIjrqLjshLjqs4TroZzrgpjslYTqsIDsnpDtm4zrpa3tlZzqsJzrsJzsnpDrpbzrp4zrk6TslrTqsIDsnpA=